version: "3"

services:
  moodle:
    ports:
      - 80:80
    volumes:
      - ./moodle-3.7-apache/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh

  db:
    hostname: db
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: "${MOODLE_MYSQL_USER}"
      MYSQL_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
    networks:
      - backend
    volumes:
      - ./bbdd:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d

  phpmyadmin:
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on: [db]
    volumes:
      - /sessions
    networks:
      - frontend
      - backend
    ports:
      - 82:80
